# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from actuator_sim.interface import actuator_pb2 as actuator__pb2

GRPC_GENERATED_VERSION = '1.80.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in actuator_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class ActuatorServiceStub(object):
    """ActuatorService provides control and telemetry for a simulated actuator.
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.SetPosition = channel.unary_unary(
                '/actuator.ActuatorService/SetPosition',
                request_serializer=actuator__pb2.SetPositionRequest.SerializeToString,
                response_deserializer=actuator__pb2.CommandResponse.FromString,
                _registered_method=True)
        self.SetVelocity = channel.unary_unary(
                '/actuator.ActuatorService/SetVelocity',
                request_serializer=actuator__pb2.SetVelocityRequest.SerializeToString,
                response_deserializer=actuator__pb2.CommandResponse.FromString,
                _registered_method=True)
        self.SetTorque = channel.unary_unary(
                '/actuator.ActuatorService/SetTorque',
                request_serializer=actuator__pb2.SetTorqueRequest.SerializeToString,
                response_deserializer=actuator__pb2.CommandResponse.FromString,
                _registered_method=True)
        self.ReadPosition = channel.unary_unary(
                '/actuator.ActuatorService/ReadPosition',
                request_serializer=actuator__pb2.ReadRequest.SerializeToString,
                response_deserializer=actuator__pb2.PositionResponse.FromString,
                _registered_method=True)
        self.ReadVelocity = channel.unary_unary(
                '/actuator.ActuatorService/ReadVelocity',
                request_serializer=actuator__pb2.ReadRequest.SerializeToString,
                response_deserializer=actuator__pb2.VelocityResponse.FromString,
                _registered_method=True)
        self.ReadCurrent = channel.unary_unary(
                '/actuator.ActuatorService/ReadCurrent',
                request_serializer=actuator__pb2.ReadRequest.SerializeToString,
                response_deserializer=actuator__pb2.CurrentResponse.FromString,
                _registered_method=True)


class ActuatorServiceServicer(object):
    """ActuatorService provides control and telemetry for a simulated actuator.
    """

    def SetPosition(self, request, context):
        """Command RPCs — write control targets
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SetVelocity(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SetTorque(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ReadPosition(self, request, context):
        """Telemetry RPCs — read current state
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ReadVelocity(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ReadCurrent(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_ActuatorServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'SetPosition': grpc.unary_unary_rpc_method_handler(
                    servicer.SetPosition,
                    request_deserializer=actuator__pb2.SetPositionRequest.FromString,
                    response_serializer=actuator__pb2.CommandResponse.SerializeToString,
            ),
            'SetVelocity': grpc.unary_unary_rpc_method_handler(
                    servicer.SetVelocity,
                    request_deserializer=actuator__pb2.SetVelocityRequest.FromString,
                    response_serializer=actuator__pb2.CommandResponse.SerializeToString,
            ),
            'SetTorque': grpc.unary_unary_rpc_method_handler(
                    servicer.SetTorque,
                    request_deserializer=actuator__pb2.SetTorqueRequest.FromString,
                    response_serializer=actuator__pb2.CommandResponse.SerializeToString,
            ),
            'ReadPosition': grpc.unary_unary_rpc_method_handler(
                    servicer.ReadPosition,
                    request_deserializer=actuator__pb2.ReadRequest.FromString,
                    response_serializer=actuator__pb2.PositionResponse.SerializeToString,
            ),
            'ReadVelocity': grpc.unary_unary_rpc_method_handler(
                    servicer.ReadVelocity,
                    request_deserializer=actuator__pb2.ReadRequest.FromString,
                    response_serializer=actuator__pb2.VelocityResponse.SerializeToString,
            ),
            'ReadCurrent': grpc.unary_unary_rpc_method_handler(
                    servicer.ReadCurrent,
                    request_deserializer=actuator__pb2.ReadRequest.FromString,
                    response_serializer=actuator__pb2.CurrentResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'actuator.ActuatorService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('actuator.ActuatorService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class ActuatorService(object):
    """ActuatorService provides control and telemetry for a simulated actuator.
    """

    @staticmethod
    def SetPosition(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/actuator.ActuatorService/SetPosition',
            actuator__pb2.SetPositionRequest.SerializeToString,
            actuator__pb2.CommandResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def SetVelocity(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/actuator.ActuatorService/SetVelocity',
            actuator__pb2.SetVelocityRequest.SerializeToString,
            actuator__pb2.CommandResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def SetTorque(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/actuator.ActuatorService/SetTorque',
            actuator__pb2.SetTorqueRequest.SerializeToString,
            actuator__pb2.CommandResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ReadPosition(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/actuator.ActuatorService/ReadPosition',
            actuator__pb2.ReadRequest.SerializeToString,
            actuator__pb2.PositionResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ReadVelocity(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/actuator.ActuatorService/ReadVelocity',
            actuator__pb2.ReadRequest.SerializeToString,
            actuator__pb2.VelocityResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ReadCurrent(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/actuator.ActuatorService/ReadCurrent',
            actuator__pb2.ReadRequest.SerializeToString,
            actuator__pb2.CurrentResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
