# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: actuator.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'actuator.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0e\x61\x63tuator.proto\x12\x08\x61\x63tuator\"#\n\x12SetPositionRequest\x12\r\n\x05\x61ngle\x18\x01 \x01(\x01\"&\n\x12SetVelocityRequest\x12\x10\n\x08velocity\x18\x01 \x01(\x01\"\"\n\x10SetTorqueRequest\x12\x0e\n\x06torque\x18\x01 \x01(\x01\"\r\n\x0bReadRequest\"3\n\x0f\x43ommandResponse\x12\x0f\n\x07success\x18\x01 \x01(\x08\x12\x0f\n\x07message\x18\x02 \x01(\t\"!\n\x10PositionResponse\x12\r\n\x05\x61ngle\x18\x01 \x01(\x01\"$\n\x10VelocityResponse\x12\x10\n\x08velocity\x18\x01 \x01(\x01\"\"\n\x0f\x43urrentResponse\x12\x0f\n\x07\x63urrent\x18\x01 \x01(\x01\x32\xac\x03\n\x0f\x41\x63tuatorService\x12\x46\n\x0bSetPosition\x12\x1c.actuator.SetPositionRequest\x1a\x19.actuator.CommandResponse\x12\x46\n\x0bSetVelocity\x12\x1c.actuator.SetVelocityRequest\x1a\x19.actuator.CommandResponse\x12\x42\n\tSetTorque\x12\x1a.actuator.SetTorqueRequest\x1a\x19.actuator.CommandResponse\x12\x41\n\x0cReadPosition\x12\x15.actuator.ReadRequest\x1a\x1a.actuator.PositionResponse\x12\x41\n\x0cReadVelocity\x12\x15.actuator.ReadRequest\x1a\x1a.actuator.VelocityResponse\x12?\n\x0bReadCurrent\x12\x15.actuator.ReadRequest\x1a\x19.actuator.CurrentResponseB\x14Z\x12\x61\x63tuator_sim/protob\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'actuator_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'Z\022actuator_sim/proto'
  _globals['_SETPOSITIONREQUEST']._serialized_start=28
  _globals['_SETPOSITIONREQUEST']._serialized_end=63
  _globals['_SETVELOCITYREQUEST']._serialized_start=65
  _globals['_SETVELOCITYREQUEST']._serialized_end=103
  _globals['_SETTORQUEREQUEST']._serialized_start=105
  _globals['_SETTORQUEREQUEST']._serialized_end=139
  _globals['_READREQUEST']._serialized_start=141
  _globals['_READREQUEST']._serialized_end=154
  _globals['_COMMANDRESPONSE']._serialized_start=156
  _globals['_COMMANDRESPONSE']._serialized_end=207
  _globals['_POSITIONRESPONSE']._serialized_start=209
  _globals['_POSITIONRESPONSE']._serialized_end=242
  _globals['_VELOCITYRESPONSE']._serialized_start=244
  _globals['_VELOCITYRESPONSE']._serialized_end=280
  _globals['_CURRENTRESPONSE']._serialized_start=282
  _globals['_CURRENTRESPONSE']._serialized_end=316
  _globals['_ACTUATORSERVICE']._serialized_start=319
  _globals['_ACTUATORSERVICE']._serialized_end=747
# @@protoc_insertion_point(module_scope)
