#!/usr/bin/env bash
# generate_public_docs.sh
#
# Generates real static documentation into public-ui/public/docs/ from:
#   1. FastAPI brain → OpenAPI JSON rendered with Redoc standalone
#   2. Rust workspace → cargo doc HTML
#
# Requirements (all available in the CI image):
#   python3, pip (brain deps installed), cargo, rustdoc
#
set -euo pipefail

ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
DOCS_OUT="$ROOT/public-ui/public/docs"
API_OUT="$DOCS_OUT/api"
RUST_OUT="$DOCS_OUT/rust"

mkdir -p "$API_OUT" "$RUST_OUT"

# ── 1. FastAPI OpenAPI → Redoc standalone HTML ────────────────────────────────
echo "==> Extracting FastAPI OpenAPI schema..."
python3 "$ROOT/scripts/extract_openapi.py" > "$API_OUT/openapi.json"

# Keep public branding consistent for hosted docs.
API_OUT="$API_OUT" python3 - <<'PY'
import os
import json
from pathlib import Path

path = Path(os.environ["API_OUT"]) / "openapi.json"
doc = json.loads(path.read_text())
info = doc.setdefault("info", {})
if info.get("title") == "Brain API":
  info["title"] = "Jog Actuator API"
if info.get("description") == "Smart Actuator Brain — REST interface":
  info["description"] = "Jog Actuator Brain — REST interface"
path.write_text(json.dumps(doc, indent=2))
PY

echo "==> Rendering Redoc standalone..."
# Redoc standalone: embed the spec inline so no runtime fetch is needed.
REDOC_CDN="https://cdn.jsdelivr.net/npm/redoc@latest/bundles/redoc.standalone.js"
cat > "$API_OUT/index.html" <<HTML
<!doctype html>
<html lang="en">
<head>
  <meta charset="utf-8">
  <title>jog actuator REST API</title>
  <meta name="viewport" content="width=device-width,initial-scale=1">
  <style>body{margin:0;padding:0}</style>
</head>
<body>
  <redoc spec-url="openapi.json"
         expand-responses="all"
         required-props-first="true"
         sort-props-alphabetically="false"
         native-scrollbars="true">
  </redoc>
  <script src="${REDOC_CDN}"></script>
</body>
</html>
HTML

echo "==> FastAPI docs done → $API_OUT/index.html"

# ── 2. Rust workspace → cargo doc ────────────────────────────────────────────
echo "==> Running cargo doc..."
(
  cd "$ROOT/smart-actuator"
  cargo doc \
    --workspace \
    --no-deps \
    --document-private-items \
    2>&1
)

# Copy the generated HTML to our docs output.
CARGO_DOC_SRC="$ROOT/smart-actuator/target/doc"
if [[ -d "$CARGO_DOC_SRC" ]]; then
  cp -r "$CARGO_DOC_SRC/." "$RUST_OUT/"
  echo "==> Rust docs done → $RUST_OUT/"
fi

# ── 3. Top-level docs index ───────────────────────────────────────────────────
cat > "$DOCS_OUT/index.html" <<'HTML'
<!doctype html>
<html lang="en">
<head>
  <meta charset="utf-8">
  <title>jog actuator docs</title>
  <meta name="viewport" content="width=device-width,initial-scale=1">
  <style>
    *, *::before, *::after { box-sizing: border-box }
    body { margin: 0; padding: 0 24px 48px; font-family: ui-sans-serif, system-ui, sans-serif; background: #09070f; color: #f3f4f6; }
    h1 { font-size: 32px; font-weight: 800; letter-spacing: -0.02em; margin: 48px 0 8px; }
    p  { color: #9ca3af; margin: 0 0 32px; }
    .grid { display: grid; grid-template-columns: repeat(auto-fit, minmax(280px, 1fr)); gap: 16px; }
    .card { background: #12101b; border: 1px solid #2a2640; border-radius: 12px; padding: 20px 24px; }
    .card h2 { font-size: 14px; font-weight: 600; color: #c084fc; margin: 0 0 6px; }
    .card p  { font-size: 13px; line-height: 1.6; color: #9ca3af; margin: 0 0 14px; }
    a { color: #c084fc; text-decoration: none; font-size: 13px; font-weight: 500; }
    a:hover { text-decoration: underline; }
    .back { display: inline-block; margin: 24px 0 0; font-size: 13px; color: #6b7280; }
  </style>
</head>
<body>
  <a href="/" class="back">← jogactuators.com</a>
  <h1>jog actuator docs</h1>
  <p>Auto-generated on every release from project sources.</p>

  <div class="grid">
    <div class="card">
      <h2>REST API Reference</h2>
      <p>All Brain HTTP endpoints, request/response schemas, and auth details — generated from FastAPI OpenAPI.</p>
      <a href="api/index.html">View REST API →</a>
    </div>
    <div class="card">
      <h2>Rust Crate Docs</h2>
      <p>actuator-core, actuator-plant, actuator-sim, actuator-proto, controller-sidecar — generated by rustdoc.</p>
      <a href="rust/actuator_core/index.html">View Rust docs →</a>
    </div>
    <div class="card">
      <h2>Proto Definitions</h2>
      <p>Source protobuf definitions for actuator, brain, sidecar, and sim RPC services.</p>
      <a href="https://github.com/ambientlabscomputing/smart-actuator/tree/develop/smart-actuator/proto" target="_blank" rel="noopener">View on GitHub →</a>
    </div>
    <div class="card">
      <h2>Architecture RFDs</h2>
      <p>Design decisions and rationale — Request for Discussion documents from the repo.</p>
      <a href="https://github.com/ambientlabscomputing/smart-actuator/tree/develop/RFDs" target="_blank" rel="noopener">View RFDs →</a>
    </div>
  </div>
</body>
</html>
HTML

echo "==> Docs index done → $DOCS_OUT/index.html"
echo "==> All public docs generated."
